<?php
/** @var Test\Task\Block\RandomProduct $block */
/** @var Test\Task\ViewModel\RandomProductViewModel $viewModel */
$viewModel = $block->getViewModel();
?>
<h2><?= $block->getBlockTitle(); ?></h2>
<div class="product-wrapper">
    <?= $viewModel->getProductImage()->toHtml(); ?>
    <p><?= $viewModel->getProductName(); ?></p>
    <span><?= $viewModel->getProductPrice(); ?></span>

    <form data-role="tocart-form" action="<?= $viewModel->getAddToCartUrl() ?>" method="post">
        <?= $block->getBlockHtml('formkey') ?>
        <div class="btn">
            <button type="submit" title="Add to Cart" class="action tocart primary">
                <span>Add to Cart</span>
            </button>
        </div>
    </form>
</div>
