<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Test\Task\ViewModel\RandomProductViewModel $vm */
$vm = $block->getViewModel();
?>
<h1><?= $vm->getBlockTitle(); ?></h1>
<h1><?= $vm->getProductImage()->toHtml(); ?></h1>

<h4><?= $vm->getProductName(); ?></h4>
<h4><?= $vm->getProductPrice(); ?></h4>

<form data-role="tocart-form" action="<?= $vm->getAddToCartUrl() ?>" method="post">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="btn">
        <button type="submit" title="Add to Cart" class="action tocart primary">
            <span>Add to Cart</span>
        </button>
    </div>
</form>
